[telegram]
# Get your API ID/HASH from https://my.telegram.org/auth
# Replace these with your actual credentials
phone_number = "+1234567890"
api_id = 12345678
api_hash = "your_api_hash_here"

[sending]
# The send interval is how long to wait between sending messages (in seconds)
send_interval = 2
# The loop interval is how long to wait before re-sending messages to all groups (in seconds)
loop_interval = 300

[rate_limiting]
# Maximum requests per time window
max_requests = 20
# Time window in seconds
time_window = 60
# Maximum backoff time in seconds
max_backoff = 300

[auto_join]
# Delay between joining groups (in seconds)
join_delay = 5
# Maximum groups to join per session
max_groups_per_session = 50

[health_check]
# Minimum number of members required for a group to be considered healthy
min_members = 10
# Maximum number of members (groups with more are considered spam)
max_members = 100000
# Maximum days since last activity for a group to be considered active
max_inactive_days = 30
# Whether to skip channels (only join groups)
skip_channels = true
# Whether to check group activity before joining
check_activity = true 